language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t amkord/dockerfundamentals -f Dockerfile.dev . #tagging image as we don't have access to the container id generated after build


script:
  - docker run -e CI=true amkord/dockerfundamentals npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: docker
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-114151569823"
  bucket_path: "docker"
  on:
    branch: master # only deploy when code is pushed to master branch
  


